apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: topcv
  namespace: elastic-stack
spec:
  version: 9.3.3
  count: 1
  elasticsearchRef:
    name: topcv
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m